# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2564c9315549a760188c28862324d5e70c02ec54b3404e61e24067406afbede008081f2936364096088e8b5aa4ccb3fe08572e8cb107463bbd8b5f363ecf5ed

test:
  secret_key_base: 882313a7045841683d5f1ac195a4fb230a4240b10d38247d44fd38104dea644b52d63c20107d5d821b042f9f2c407cae09854130b9cc072d8488de8b9bb5f830

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
